### PR TITLE
feat(NaturePathfinder): setup basic proj for algorithm

### PR DESCRIPTION
**Pull request by Nah-Nova**
## 🎟️ Issue

BEN-98: Implement Dijkstra’s algorithm to calculate the shortest route between nature areas in Zuid Nederland.

## ✨ Description

This PR adds an implementation of Dijkstra’s algorithm to calculate the shortest route between specified nature areas in Zuid Nederland. The graph of areas is constructed using hardcoded coordinates, and distances between centroids are calculated using the Haversine formula. Console output has been added to visualize the algorithm’s step-by-step execution, including distance updates and path reconstruction.

## 🕵 Background

This change is being made to provide a tool for calculating and visualizing the shortest path between nature areas based on geographic distances. It’s intended for use in scenarios where visitors may want to explore optimal routes between natural landmarks in Limburg and nearby regions.

## 📝 Resources
Dijkstra’s Algorithm Overview: [Dijkstra’s Algorithm - Wikipedia](https://en.wikipedia.org/wiki/Dijkstra%27s_algorithm)
Haversine Formula for Distance Calculation: [Haversine Formula - Wikipedia](https://en.wikipedia.org/wiki/Haversine_formula)
Big O Notation: Notes in code comments describe the time complexity for each function

### CODE REVIEW

**Review by paulib2000 — APPROVED** [review]
Ziet er top uit voor zover ik het kan lezen

**Review by broertje-cloud — APPROVED** [review]
LGTM

**Review by Underlyingglitch — APPROVED** [review]
Lego Disney - Glasses

**Review by broertje-cloud — APPROVED** [review]
lgtm

**Pull request merged**
